### ISSUE TITLE
Issues v0.1.0 and for next release

### ISSUE THREAD

**Issue by abaron** [abaron/bulk-domain-availability#1]
Issues
- [x] Availability Counter not set to 0 after reset
- [ ] ?

Todo
- [ ] Click domain name, auto select all
- [ ] Update readme, recursive clone, wiki link, etc
- [ ] ?

**Comment by chinmay241** [comment]
It would be nice to add select all TLD while searching. As well as ability able to modify the pre-selected TLD (com,net and org).

Edit: The Dependency package of HelgeSverre/Domain-Availability is also 1.5.0 and 0.23 seems running older version of PHP.
